Create Base APIs
yoursweet667/Messenger_Backend pull request #1
Opened 2021-06-15 15:24 UTC by yoursweet667

2021-06-15 17:22 UTC, aleksei-budiak requested changes

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +        404:
404 вполне валидный код, но он действительно необходим для запросов, в которых ты ищешь уникальную сущность. Например, GET /users/{userId}. 

Здесь же у тебя может вернуться несколько результатов, один или ноль. Ноль результатов в данном случае не является ошибкой и ответ мог бы выглядеть так:
```
200 OK
...
{
  "users": []
}
```

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +        204:
Когда ты создаешь новую сущность, обычно ты даешь серверу сгенерировать для нее ID.
Поэтому, обычно для POST запросов 204 код не очень подходит - ты не узнаешь ID созданной сущности.
Здесь лучше возвращать полную сущность юзера.

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +        302:
302 совсем не подходит.

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +      - Messages
Может перенести в Conversations? Сообщения вне чата не могут существовать.

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +      description: Get message
Внимательно следи за единственным и множественным числом, когда пишешь документацию

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +          name: username
На что будет влиять этот параметр?

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +        204:
Опять же, если ты не запрашиваешь что-то уникальное и тебе может вернуться множество (или 0) результатов, то лучше вместо 204 использовать 200. Хотя это не железное правило :)

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +        204:
Вот, кстати, хороший пример, когда 204 выглядит вполне логично в POST запросе.
1. Клиенту не особо-то и нужно знать messageId, если у тебя не будет функционала удаления сообщения.
2. Позже, клиент все равно получит это сообщение и его ID из GET /conversations/{converstionId}/messages запроса.

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +        204:
Плюс здесь в хоть и небольшой, но экономии траффика.

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +  /conversations/{converstionId}/messages:
А что, если в чате уже миллион сообщений? Каждый ответ будет получать их все?
Следует добавить параметры, позволяющие пропустить сообщения, которые у клиента уже есть.
Такой функционал обычно называют pagination - клиенты могут получать сообщения "постранично". 

Вот тут объясняется чуть подробнее: https://cloud.yandex.ru/docs/api-design-guide/concepts/pagination

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +  /conversations/{converstionId}/messages:
Я бы предложил добавить такие параметры:
- offset - номер первого сообщения, которое должен вернуть сервер
- limit - количество сообщений, которые должен вернуть сервер

Если я пошлю запрос с offset=60 и limit=20, то сервер должен будет мне вернуть сообщения с номера 60 по 80

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +    Conversation:
Проверь-ка эту схему. Что-то пошло не так.

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +    User:
У каждой сущности должен быть ID.

2021-06-15 17:22 UTC, aleksei-budiak commented on API/openapi.yaml
> +    Messages:
Тут тоже что-то пошло не так.

2021-06-16 11:50 UTC, yoursweet667 commented on API/openapi.yaml
> +      operationId: CreateChat
Хорошо, исправил

2021-06-16 11:51 UTC, yoursweet667 commented on API/openapi.yaml
> +      operationId: AddUser
Исправлено

2021-06-16 11:53 UTC, yoursweet667 commented on API/openapi.yaml
> +            type: number
Изменил на string

2021-06-16 14:15 UTC, yoursweet667 commented on API/openapi.yaml
> +          name: username
Изменил на userId

2021-06-16 14:15 UTC, yoursweet667 commented on API/openapi.yaml
> +        302:
Изменил 302 на 409

2021-06-16 14:24 UTC, yoursweet667 commented on API/openapi.yaml
> +      description: Get user
Данный API действительно ищет юзера, немного изменил принцип поиска, он будет осуществляться по userId, он уникален

2021-06-16 14:31 UTC, yoursweet667 commented on API/openapi.yaml
> +        204:
Исправлено

2021-06-16 14:32 UTC, yoursweet667 commented on API/openapi.yaml
> +        302:
Исправлено

2021-06-16 14:48 UTC, yoursweet667 commented on API/openapi.yaml
> +      - Messages
Перенес в Conversations

2021-06-16 14:51 UTC, yoursweet667 commented on API/openapi.yaml
> +        404:
В моем случае подойдет 404, тк поиск будет осуществляться по userId - это уникальное значение

2021-06-16 15:01 UTC, yoursweet667 commented on API/openapi.yaml
> +          name: username
Нам действительно не нужен данный параметр, убрал

2021-06-16 15:05 UTC, yoursweet667 commented on API/openapi.yaml
> +        204:
Принял :)

2021-06-16 15:21 UTC, yoursweet667 commented on API/openapi.yaml
> +    Messages:
Исправил

2021-06-16 15:21 UTC, yoursweet667 commented on API/openapi.yaml
> +    Conversation:
Исправил

2021-06-16 15:33 UTC, yoursweet667 commented on API/openapi.yaml
> +  /conversations/{converstionId}/messages:
Хорошая идея, добавил нужные параметры

2021-06-19 08:21 UTC, aleksei-budiak requested changes

2021-06-19 08:27 UTC, yoursweet667 commented on API/openapi.yaml
> +      - User
Исправлено

2021-06-19 08:28 UTC, yoursweet667 commented on API/openapi.yaml
> +          "User":
Исправлено

2021-06-19 08:29 UTC, yoursweet667 commented on API/openapi.yaml
> +        message:
Исправлено

2021-06-19 08:32 UTC, yoursweet667 commented on API/openapi.yaml
> +          "message":
Исправлено

2021-06-22 17:45 UTC, merged